language: minimal
dist: xenial
script:
- make tests
deploy:
  provider: script
  script: make publish
  on:
    tags: true
env:
  global:
  - secure: IMMnTIhryj9z0YB8SynHmwoxhQeIZDF5QHZQP/JIvNtCPjwUYFY2YHHQ2Jj1LfA6R9qkBE8W1HvIvDH3USFYhjHYeHUQh9ZO5HadX7gptTLuqQqYAfx88uufK0NmJ0VInEyknSu0phZhydqjJliiXT2pyReNox0wVxo1SrEEgbBtHDARftRYk5nMuN572nRDbe9PtleR12rFw984Kj/pc3y69Zj5iGpBOUBj/GIk5cGWUFrpYFlfCv0/OhH0wIuw0HKvxFUrnXdkGIS7Oogq7qU1b+5rRW5TFeWGrVUrX4m5N42RzKA0azLpwZA+shSRM7bouDeEqjVwF73vVpp3Eom03SC+DSEGXE34Q3j6Q7am3GxPYzvEtzZtC50lo0wpXyg43zmhQn4x64H7UU6n5db9nKhAGx7bUH4qzyfYoI+3fMQwXf8oumSsmbjSE4pXpvNee0Wcmi9W0hYBLrS4p9YcKkw6Q+WrHGplKkfKSLC5sd1VOuy4bcmgpYZRH/cpEVfj6gs3kWdJMer++liwl6D2IFVfRS4ozCP5xnH1NJLCp5BFHRlnN76P5fdCDF5T7y25M33N3TwBJ8YoS0+w8iNLEwjMkbdFtBDjaJxlIJBGLbsCHIjZ/ojjDBim323cCLTNkbzfn868INGm9Cyw8o4FvQIHysxNJSnWtLjsseM=
  - secure: SaQ7HPjwZytYRWucOXyPyJkW3D3CXM4GT9WhLQI6f1ye6h7HLA97dahK7MJy9VizRweb4pzyjn0+J8Ff6v1p+MU3fdOxhjcsMw2XoLCaY/Gt6EzFdFmm9eKfCDEI/FUtJc+WhNBSwOlZBPsUIDrXC0wHtVXScrXJ8IWHSiKwKBmNH3Z9Bkvrlu2BOweOJAnSpoXhESHXves+KdP2EYehlv4K9zsZHhkbjomTXyTp2VhZoGDiVAcOOJj0B+QnBUZ1dwZj4w6L7J6wWteTcbkGyviUeV60zRcPS7cpUKMG2aa/a3M35XbMCCkhnK3Taeb1GMjxVZMgjjVadHr9Gn2XtYGPBj3UjTwac6mmbrVi428f/6ESqOUb76PS1XNwzl0Yp7uVrzqWT7Go1CeHAcww33YfCsqqLzaMZOAyY7iDStrfm8DIGElCcUY522JQPRSOuRrN88U2TepIF1TEzvBtIahiW7jTYh2RNpATt0CXCwSuUvNxDqyQnFJETtHt+qkYp0IR//RuiwMN4U47BjkOWtfEt/vZ0VSBZPmNNCeLTrrWOvQLFNKM7iBTBVf5PBxtBRAVSvBhxmBBhZ1UYv6550+i5fJ5qcv/1SKd8YiuIMppkaAldP7NqZQwZDwM8Oc9xpJZ0eqnGiLzUiJx0sF4KliU4mEvUxXx8J7rIAWJZ9Y=
